### ISSUE TITLE
Emoticons donot appear

### ISSUE THREAD

**Issue by mohattia22** [SamsungInternet/snapwat#32]
There are only sympols instead of emoticons

**Comment by poshaughnessy** [comment]
Hi. Thanks for raising this. It sounds like your platform doesn't have native emoji support. Which device/OS are you using?

**Comment by mohattia22** [comment]
Hey,thanks for your great script.I used chrome android huwaui ,it worked with demo but not workes in my web.iam using shared hosting without https. What should I do?

**Comment by mohattia22** [comment]
The problem is that I cannot save index.html file as utf-8 .and it always be saved as window.....do you know a simple way to support emoji

**Comment by mohattia22** [comment]
How to make emotij buttons with window 1252 instead of utf-8 ?

**Comment by mohattia22** [comment]
Hey, I still have a problem with emoji .it doesnot appear well and it
looklike text.I tried snapwat in chrome .mozilla desktop.android huawei and
infinx android ..it didnot work in all .but work in demo link ..could you
help me in this?.thanks inadvance.

بتاريخ ٠٧‏/٠٢‏/٢٠١٧ ١١:٥٤ ص، كتب "poshaughnessy" <notifications@github.com>:

**Comment by poshaughnessy** [comment]
Hi @mohattia22. Perhaps you can try a different editor that supports utf-8 encoding? Atom seems to work pretty well with them.

Otherwise you could revert to using actual images if you like - that's what my demo had originally. Here's the commit where I switched the emoji images to unicode: 
https://github.com/SamsungInternet/snapwat/commit/12410bdb5395eccc97b0fc3db70fdaa95f48e9d7 

I got the images from here:
http://emojione.com/developers/

You would need https for the service worker support, but the rest of the demo should work on http...

**Comment by mohattia22** [comment]
I tried to revert emoji as images but this make an error.could you send me
bundle.js file of the demo.

بتاريخ ١٣‏/٠٢‏/٢٠١٧ ١٢:١٢ ص، كتب "poshaughnessy" <notifications@github.com>:

**Comment by mohattia22** [comment]
plz send me snapwat like demo(emoji as images) as I still have error after
modifying files


بتاريخ ١٨‏/٠٢‏/٢٠١٧ ١٢:٥٣ م، كتب "mohamed attia" <mohattia22@gmail.com>:

**Comment by mohattia22** [comment]
Switch the camera is absent after making changes to revert emoji as images.
This is the web http://liaizone.com/50/public/index.html

بتاريخ ٠٧‏/٠٢‏/٢٠١٧ ١١:٥٤ ص، كتب "poshaughnessy" <notifications@github.com>:

**Comment by poshaughnessy** [comment]
Sorry, when I said: _"You would need https for the service worker support, but the rest of the demo should work on http..."_ I was wrong. getUserMedia (for the live camera feed) now won't working without https:

<img width="645" alt="screen shot 2017-03-03 at 14 03 26" src="https://cloud.githubusercontent.com/assets/151207/23553795/3994f30e-001a-11e7-8f15-8a482f2facd4.png">

If you don't mind, I'll close this issue because it's really for issues with the version shared here, and the issues you're having are with your forked version that you're hosting separately. Hope you manage to fix it up OK though!
