### ISSUE TITLE
using version2 how to invite users to add snapwat to home screen?

### ISSUE THREAD

**Issue by mohattia22** [SamsungInternet/snapwat#37]

**Comment by poshaughnessy** [comment]
Hi @mohattia22.

Some browsers have Add To Home Screen prompts that they show automatically after determining user engagement:

![1-bzr6hin0dfym9shwz-pf1g](https://user-images.githubusercontent.com/151207/28620463-f71f8fc2-7204-11e7-9061-4d3703f2d63b.png)

Browsers like Samsung Internet also have ambient badging which provides a handy shortcut:

![1-ezqwrswi2juil60utodkxa 1](https://user-images.githubusercontent.com/151207/28620489-061cc72e-7205-11e7-8ed5-e309ba025341.png)

I've written more about this here in case it's useful:

https://medium.com/samsung-internet-dev/heres-what-you-get-for-free-with-a-progressive-web-app-74b7ac5bdb3a

I would try to avoid introducing your own separate prompts to ask people to add it to their homescreen, since it is more likely to annoy users. They should be able to use it fine without launching it standalone too.
